<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="coloredTree" nsURI="http://cs.york.ac.uk/ColoredTree/1.0" nsPrefix="coloredTree">
  <eClassifiers xsi:type="ecore:EClass" name="HueTree">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//HueTree" containment="true" eOpposite="#//HueTree/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//HueTree" eOpposite="#//HueTree/children"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="#//Color"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Color">
    <eLiterals name="red"/>
    <eLiterals name="green" value="1" literal="green"/>
    <eLiterals name="blue" value="2"/>
  </eClassifiers>
</ecore:EPackage>
