<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="familyTree" nsURI="http://cs.york.ac.uk/es/FamilyTree" nsPrefix="familiyTree">
  <eClassifiers xsi:type="ecore:EClass" name="FamilyTree">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leaves" upperBound="-1"
        eType="#//Person" eOpposite="#//Person/tree"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="father" eType="#//Male"
        eOpposite="#//Male/children"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mother" eType="#//Female"
        eOpposite="#//Female/children"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tree" eType="#//FamilyTree"
        eOpposite="#//FamilyTree/leaves"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Male" eSuperTypes="#//Person">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wife" eType="#//Female"
        eOpposite="#//Female/husband"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" eType="#//Person"
        eOpposite="#//Person/father"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Female" eSuperTypes="#//Person">
    <eStructuralFeatures xsi:type="ecore:EReference" name="husband" eType="#//Male"
        eOpposite="#//Male/wife"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" eType="#//Person"
        eOpposite="#//Person/mother"/>
  </eClassifiers>
</ecore:EPackage>
